---
# command_line - This sets up Oh My ZSH, Custom plugins, themes, aliases, etc.
# and organizes them each into a respective file.  This allows for easier
# customization for your unique needs. Starship is an agnostic shell that is
# used by default.

- shell:
    - description: '6. Setting up Command Line Tools'
      command: './onboarding_bin/install-oh-my-zsh.sh'

- link:
    ~/.zlogin:
      force: true
      path: shell/.zlogin
      stdout: true
    ~/.zprofile:
      force: true
      path: shell/.zprofile
      stdout: true
    ~/.theme.zsh:
      force: true
      path: shell/.theme.zsh
    ~/.plugins.zsh:
      force: true
      path: shell/.plugins.zsh
    ~/.functions.zsh:
      force: true
      path: shell/.functions.zsh
    ~/.aliases.zsh:
      force: true
      path: shell/.aliases.zsh
    ~/.zshrc:
      force: true
      path: shell/.zshrc
    ~/.m1-fixes.zsh:
      force: true
      path: shell/.m1-fixes.zsh

# Terminal Settings, Profile, and Configuration
# TODO: Add zsh to restart shell
- shell:
    - echo '4. Setting up iTerm Profile and Configuration...'
- link:
    ~/iterm-profile-dotfiles.json:
      force: true
      path: shell/iterm-profile-dotfiles.json
    ~/iterm-profile-dotfiles.itermkeymap:
      force: true
      path: shell/iterm-profile-dotfiles.itermkeymap
    ~/com.googlecode.iterm2.plist:
      force: true
      path: shell/com.googlecode.iterm2.plist
    ~/.iterm2_shell_integration.zsh:
      force: true
      path: shell/.iterm2_shell_integration.zsh

- shell:
    # iTerm Configuration, Profile, and Settings
    # Specify the preferences directory
    - defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string '~/'

    # Tell iTerm2 to use the custom preferences in the directory
    - defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true
    # TODO: Please complete the two items below to finish the setup process.
    - echo "[TODO] iTerm2 profile - Open iTerm2 -> Preferences"
    - echo "-> Profiles -> Other Actions -> Import JSON Profiles"
    - echo "Select the profile from \n
      ~/iterm-profile-front-end-engineering.json"
    - echo "[TODO] Click Other Actions... -> \n Set as Default"
    - echo "[TODO] iTerm2 keymap - Open iTerm2 \n
      -> Preferences -> Keys -> Presets... ->"
    - echo "[TODO] Import... Select the keymap \n
      from ~/iterm-profile-front-end-engineering.json"
