# engineering_yaml - Linking your YAML default linting and formatting

- shell:
    - echo "Setting up Software Engineering - YAML linting and formatting rules..."

- link:
    ~/.yamllint.yml: engineering/yaml/.yamllint.yml
