---
# engineering_linting_styles - Links global stylelint configs and ignores to
# your home directory.

- shell:
    - echo "Setting up Software Engineering - global styling linting..."

- link:
    ~/stylelint.config.js:
      path: engineering/styles/stylelint.config.js
    ~/.stylelintrcignore:
      path: engineering/styles/.stylelintrcignore
