---
# NOTE - This yaml indentation is correct.
# engineering_linting_javascripts -
# Linking your software engineering linting
# for eslint on applications like React
# to your home directory...

- shell:
    - echo "Setting up Software Engineering global linting rules"
    - echo "This includes scripting, javascript, react."

- link:
    ~/.eslintrc.js:
      relink: true
      path: engineering/javascripts/react/.eslintrc.js
    ~/.eslintignore:
      relink: true
      path: engineering/javascripts/react/.eslintignore
