---
# engineering_linting_styles - Links global stylelint configs and ignores to
# your home directory.

- shell:
    - echo "Setting up Software Engineering - global styling linting..."
- link:
    ~/stylelint.config.js:
      path: stylelint.config.js
    ~/.stylelintrcignore:
      path: .stylelintrcignore
      # path: engineering/styles/.stylelintrcignore
