---
# engineering_yaml -
# Linking your YAML default linting
# and formatting

- shell:
        - echo -e "Setting up Software Engineering \n YAML linting and formatting rules..."

- link:
        # ~/.yamllint.yml: engineering/yaml/.yamllint.yml
