---
# engineering_formatters
# Linking your software engineering formatters like
# editorconfig, prettier, and htmlhint to your home directory...

- shell:
    - echo -e "Setting up Software Engineering \n
      global formatting rules..."
- link:
    # ~/.editorconfig: engineering/formatters/.editorconfig
    ~/.prettierrc.js:
      force: true
      path: engineering/formatters/.prettierrc.js
    ~/.prettierignore:
      force: true
      path: engineering/formatters/.prettierignore
    ~/.htmlhintrc:
      force: true
      path: engineering/formatters/.htmlhintrc
