---
# homebrew_devops - A DevOps configuration.
# This uses brew bundle to install a number of
# DevOps packages and required libraries.

- shell:
    - description: '3. Installing Homebrew Package Manager - DevOps Packages...'
      command: brew bundle --file=Brewfile.devops
      stdout: true
      stderr: true
