---
# homebrew_ruby - A Ruby on Rails configuration.
# This uses brew bundle to install a number of
# Ruby packages and required libraries.

- shell:
    - description: '3. Installing Homebrew Package Manager - Ruby Packages...'
      command: brew bundle --file=Brewfile.ruby
      stdout: true
      stderr: true
