---
# homebrew_base - A base configuration. This uses brew bundle
# to install a number of basic machine
# libraries as well as a number of default applications,
# you would want with any MacOSX machine.

- shell:
    - description: '3. Installing Homebrew Package Manager...'
      command: './onboarding_bin/install-homebrew.sh'
      stdout: true
      stderr: true

- shell:
    - description: '3. Installing Homebrew Package Manager - Base Packages...'
      command: brew bundle --file=Brewfile.base
      stdout: true
      stderr: true
