---
# homebrew_ruby - A Ruby on Rails configuration.
# This uses brew bundle to install a number of
# Ruby packages and required libraries.

- shell:
    - description: '3. Installing Homebrew Package Manager - Base Packages...'
      command: './onboarding_bin/install-homebrew.sh'
      stderr: true

- brewfile:
    - Brewfile.devops
