# ide - A base configuration. This installs vs code, sets up team settings, snippets, keybindings, and
# extensions.

- shell:
    - echo "9. Installing VS Code and extensions - Ruby provisioning settings, keybindings, snippets, etc. "

- link:
    '~/Library/Application Support/code/User/settings.json':
      path: engineering/ide/.vscode/settings.json
      force: true
    '~/Library/Application Support/code/User/tasks_ruby.json':
      path: engineering/ide/.vscode/tasks_ruby.json
      force: true
    '~/Library/Application Support/code/User/launch_ruby.json':
      path: engineering/ide/.vscode/launch_ruby.json
      force: true
- shell:
    - description: 'Installing VSCode Extensions...'
      command: './onboarding_bin/vscode-install-extensions-ruby.sh'
      stdout: true
      stderr: true
