# ide - A base configuration. This installs vs code, sets up team settings, snippets, keybindings, and
# extensions.

- shell:
    - echo "9. Installing VS Code and extensions - Provisioning settings, keybindings, snippets, etc."

- link:
    '~/Library/Application Support/code/User/settings.json':
      path: engineering/ruby/ide/.vscode/settings.json
      force: true
    '~/Library/Application Support/code/User/keybindings.json':
      path: engineering/ruby/ide/.vscode/keybindings.json
      force: true
    '~/Library/Application Support/code/User/tasks.json':
      path: engineering/ruby/ide/.vscode/tasks.json
      force: true
    '~/Library/Application Support/code/User/launch.json':
      path: engineering/ruby/ide/.vscode/launch.json
      force: true
# TODO: Need to apply an if statement in the event that the extension count is
# less than 5 extensions.
- shell:
    - code --list-extensions > engineering/ruby/ide/.vscode/extensions.txt
- vscodefile:
    file: engineering/ide/ruby/.vscode/extensions.txt
    insiders: false
