---
# initialize - This scaffolds out a folder structure
# for your team or individual situation.
# By using a uniform broad to specific structure,
# you can share aliases more
# easily across multiple teams and assume
# the same structure, locally.

- shell:
          - echo '1. Setting up MacOSX - Creating folder structures...'
          - source '.envrc'

- create:
          #   - ~/Library/LaunchAgents
          - '~/.git-template-directory'
          - '~/.git-template-directory/hooks'
          - '~/.git-template-directory/.github'
          - '~/Retail-Success'
          - '~/Retail-Success/repos'
          - '~/Retail-Success/repos/development-team'
          - '~/Retail-Success/repos/digital-products'
          - '~/Retail-Success/repos/digital-services'
          - '~/Retail-Success/repos/admins'
          - '~/Retail-Success/repos/personal'
