---
# initialize - This scaffolds out a folder structure
# for your team or individual situation.
# By using a uniform broad to specific structure,
# you can share aliases more
# easily across multiple teams and assume
# the same structure, locally.

- shell:
    - echo '1. Setting up MacOSX - Creating folder structures...'

- create:
    - ~/downloads
    - ~/downloads/databases
    - ~/alfred
    - ~/Library/LaunchAgents
    - ~/.git-template-directory
    - ~/.git-template-directory/hooks
    - ~/.git-template-directory/.github
    - ~/AMU
    - ~/AMU/repos
    - ~/AMU/repos/amu-development-team
    - ~/AMU/repos/amu-digital-products
    - ~/AMU/repos/amu-digital-services
    - ~/AMU/repos/amu-admins
    - ~/AMU/repos/personal
