---
# initialize - This scaffolds out a folder structure
# for your team or individual situation.
# By using a uniform broad to specific structure,
# you can share aliases more
# easily across multiple teams and assume
# the same structure, locally.

- shell:
        - echo '1. Setting up MacOSX - Creating folder structures...'

- create:
        #   - ~/Library/LaunchAgents
        - ~/.git-template-directory
        - ~/.git-template-directory/hooks
        - ~/.git-template-directory/.github
        - ~/$CURRENT_COMPANY
        - ~/$CURRENT_COMPANY/repos
        - ~/$CURRENT_COMPANY/repos/development-team
        - ~/$CURRENT_COMPANY/repos/digital-products
        - ~/$CURRENT_COMPANY/repos/digital-services
        - ~/$CURRENT_COMPANY/repos/admins
        - ~/$CURRENT_COMPANY/repos/personal
