# MacOSX - This sets up some sensible defaults for mac machines.  Things like
# unhiding files and folders, auto-hiding the dock, showing path in the finder
# title, etc. #TODO: Add windows support for windows-based software engineers

- shell:
    - echo '2. Setting up Mac OSX - Sensible Default Settings...'
    # Finder: show hidden files by default
    - defaults write com.apple.finder AppleShowAllFiles -bool true
    # Automatically hide and show the Dock. NOTE - It is recommended to remove
    # all the applications out of the dock unless it is opened by default when
    # starting your machine.  This keeps your UI minimal and turns the dock into
    # an easy way to see which applications are opened and which are not.
    - defaults write com.apple.dock autohide -bool true
    # Display full POSIX path as Finder window title
    - defaults write com.apple.finder _FXShowPosixPathInTitle -bool true
    # Disable the sound effects on boot
    # - sudo nvram SystemAudioVolume=" "
