---
# security - First, imports your sensitive env variables
# into the session so your personalized information
# is safely considered.
# Things like gitconfig, file pathing, jira credentials
# etc. use these variables.
# Secondly, it makes the onboarding_bin
# and your dotfiles executable.
- shell:
    - echo -e '5. Setting up Scripts and Security \n
      Copying over personalized environment variables and bin scripts...'

- link:
    ~/.envrc:
      force: true
      path: .envrc
    ~/.onboarding_bin:
      force: true
      path: ./onboarding_bin
