# Version Control
- shell:
    - echo '7. Setting up Version Control - Gitconfig and template repo...'
- link:
    ~/.git-template-directory/.github/CODEOWNERS:
      path: version-control/.git-template-directory/.github/CODEOWNERS
      relink: true
    # Leave out if no not using atlassian.
    # ~/.git-template-directory/hooks/prepare-commit-msg:
    #   path: version-control/.git-template-directory/hooks/prepare-commit-msg
    #   relink: true
    ~/.git-template-directory/.gitignore:
      path: version-control/.git-template-directory/.gitignore
      relink: true

# - shell:
#     - description: '8. Globally Configuring Git based on environment variables...'
#       command: ./onboarding_bin/setup_git.sh
