# Version Control
- shell:
    - echo '7. Setting up Version Control - Gitconfig and template repo...'
- link:
    ~/.gitconfig:
      force: true
      path: version-control/.git-template-directory/.gitconfig
    ~/.git-template-directory/.github/CODEOWNERS: version-control/.git-template-directory/.github/CODEOWNERS
    ~/.git-template-directory/hooks/prepare-commit-msg: version-control/.git-template-directory/hooks/prepare-commit-msg
    ~/.git-template-directory/.gitignore: version-control/.git-template-directory/.gitignore
