- tap:
    - caskroom/fonts
    - homebrew/dupes

- brew: [
      adns,
      autoconf,
      autojump,
      libtool,
      cmake,
      coreutils,
      docbook,
      docbook-xsl,
      font-fira-code,
      freetype,
      gcc,
      geckodriver,
      gettext,
      ghostscript,
      git,
      git-lfs,
      glib,
      gmp,
      gnu-getopt,
      gnupg,
      gnutls,
      icu4c,
      imagemagick --with-webp,
      iterm2,
      jpeg,
      krb5,
      libgcrypt,
      libheif,
      libyaml,
      mysql,
      node,
      nvm,
      pinentry,
      protobuf
      postgresql,
      rvm,
      redis,
      shellcheck,
      sqlite3,
      thefuck,
      unbound,
      unrar,
      webp,
      yamllint
      vim --with-override-system-vi,
      zsh-history-substring-search,
    ]

- cask: [
      1password,
      adobe-creative-cloud,
      alfred,
      google-backup-and-sync,
      cyberduck,
      docker,
      dropbox,
      firefox,
      gemini,
      google-chrome,
      iterm2,
      mamp,
      microsoft-teams,
      microsoft-excel,
      microsoft-powerpoint,
      microsoft-word
      nordvpn,
      onedrive,
      postman,
      rar,
      slack,
      sourcetree,
      spotify,
      visual-studio-code,
      vlc,
      zoom,
    ]
