- defaults:
    link:
      relink: true

- clean: ['~']

- link:
    .bitbucket: ~
    .p10k.zsh: ~

- create:
    - ~/downloads

- shell:
    - [git submodule update --init --recursive, Installing submodules]
