#!/usr/bin/env bash

set -e

CONFIG="install.config.yml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
  -d "${BASEDIR}" \
  --plugin-dir dotbot-brew \
  --plugin-dir dotbot-vscode \
  -c "${CONFIG}" "${@}"
