- clean: ['~']

- link:
    ~/.bitbucket: .bitbucket
    ~/.gitconfig: .gitconfig
    ~/.config: .config
    ~/.p10k.zsh: .p10k.zsh
    ~/.electron-gyp: node/.electron-gyp
    ~/.npmignore: node/.npmignore
    ~/.gemrc: ruby/.gemrc
    ~/.mkshrc: ruby/.mkshrc
    ~/.iterm2_shell_integration.zsh: .iterm2_shell_integration.zsh

- create:
    - ~/downloads

- shell:
    - [git submodule update --init --recursive, Installing submodules]
