- clean: ['~']

- link:
    ~/.bitbucket: .bitbucket
    ~/.gitconfig: .gitconfig
    ~/.electron-gyp: .electron-gyp
    ~/.config: .config
    ~/.p10k.zsh: .p10k.zsh

- create:
    - ~/downloads

- shell:
    - [git submodule update --init --recursive, Installing submodules]
