#!/usr/bin/env bash

set -e

CONFIG="install.config.yml"
DOTBOT_DIR="dotbot"
DOTBOT_BREWFILE_DIR="dotbot-brewfile"
DOTBOT_VSCODE_DIR="dotbot-vscode"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"
git submodule update --init --recursive "${DOTBOT_BREWFILE_DIR}"
git submodule update --init --recursive "${DOTBOT_VSCODE_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir dotbot-brew -c "${CONFIG}" "${@}"
