- defaults:
    link:
      create: true
      relink: true
    file:
      force: true

- clean: ['~']

- link:
    ~/.bitbucket: .bitbucket
    ~/.gitconfig: .gitconfig
    ~/.cache: .cache
    ~/.config: .config
    ~/.p10k.zsh: oh-my-zsh/custom/p10k.zsh
    ~/.oh-my-zsh: .oh-my-zsh
    ~/.p10k.zsh: .p10k.zsh
    ~/.zshrc: .zshrc
    ~/.nvm: node/.nvm
    ~/.electron-gyp: node/.electron-gyp
    ~/.node: node/.nvmrc
    ~/.npmignore: node/.npmignore
    ~/.bundle: ruby/.bundle
    ~/package.json: engineering/package.json
    ~/yarn.lock: engineering/yarn.lock
    ~/postcss.config.js: engineering/postcss.config.js
    ~/.postcssrc.yml: engineering/.postcssrc.yml
    ~/.rubocop.yml: ruby/.rubocop.yml
    ~/.gem: ruby/.gem
    ~/.gemrc: ruby/.gemrc
    ~/.mkshrc: ruby/.mkshrc
    ~/.pyenv:
      path: python/.pyenv
      create: true
    ~/Brewfile: Brewfile
    ~/Brewfile.lock.json: Brewfile.lock.json
    ~/.iterm2_shell_integration.zsh: .iterm2_shell_integration.zsh

- create:
    - ~/downloads

- brewfile:
    - Brewfile

# - vscodefile:
#    file: Vscodefile
#    insiders: true

- shell:
    - [
        'if [ -n "$BASH_VERSION" ]; then chsh -s $(which zsh); fi',
        'Changing shell to zsh if needed',
      ]
    - [nvm install "lts/*" && nvm alias default node, NVM: Installing the
          latest and setting it as default.]
    - [git submodule update --init --recursive, Installing submodules]
