- defaults:
    link:
      relink: true

- clean: ['~']

- shell:
    - xcode-select --install || true
    - git submodule update --init --recursive
    - sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" || true

- link:
    ~/.bitbucket: .bitbucket
    ~/.gitconfig: .gitconfig
    ~/.config: .config
    ~/.p10k.zsh: .p10k.zsh
    ~/.zshrc: .zshrc
    ~/.zshrc_theme.zsh: .zshrc_theme.zsh
    ~/.zshrc_plugins.zsh: .zshrc_plugins.zsh
    ~/.zshrc_functions.zsh: .zshrc_functions.zsh
    ~/.zshrc_aliases.zsh: .zshrc_aliases.zsh
    ~/.electron-gyp: node/.electron-gyp
    ~/.node: node/.nvmrc
    ~/.npmignore: node/.npmignore
    ~/.bundle: ruby/.bundle
    ~/package.json: engineering/package.json
    ~/yarn.lock: engineering/yarn.lock
    ~/.editorconfig: engineering/.editorconfig
    ~/.eslintrc.json: engineering/.eslintrc.json
    ~/.eslintignore: engineering/.eslintignore
    ~/postcss.config.js: engineering/postcss.config.js
    ~/.prettierrc.json: engineering/.prettierrc.json
    ~/.prettierignore: engineering/.prettierignore
    ~/.postcssrc.yml: engineering/.postcssrc.yml
    ~/.stylelintrc.json: engineering/.stylelintrc.json
    ~/.rubocop.yml: ruby/.rubocop.yml
    ~/.gem: ruby/.gem
    ~/.gemrc: ruby/.gemrc
    ~/.mkshrc: ruby/.mkshrc
    ~/.pyenv:
      path: python/.pyenv
      create: true
    ~/Brewfile: Brewfile
    ~/Brewfile.lock.json: Brewfile.lock.json
    ~/.iterm2_shell_integration.zsh: .iterm2_shell_integration.zsh

- create:
    - ~/downloads
    - ~/.nvm

- brewfile:
    - Brewfile

- shell:
    - [source ~/.zshrc, Sourcing .zshrc]
