- clean: ['~']

- link:
    ~/.bitbucket: .bitbucket
    ~/.gitconfig: .gitconfig
    ~/.config: .config
    ~/.oh-my-zsh: .oh-my-zsh
    ~/.p10k.zsh: .p10k.zsh
    ~/.zshrc: .zshrc
    ~/.nvm: node/.nvm
    ~/.electron-gyp: node/.electron-gyp
    ~/.node: node/.nvmrc
    ~/.npmignore: node/.npmignore
    ~/.bundle: ruby/.bundle
    ~/.gem: ruby/.gem
    ~/.gemrc: ruby/.gemrc
    ~/.mkshrc: ruby/.mkshrc
    ~/.pyenv:
      path: python/.pyenv
      create: true
    ~/Brewfile: Brewfile
    ~/.iterm2_shell_integration.zsh: .iterm2_shell_integration.zsh

- create:
    - ~/downloads

- brewfile:
    file: ~/Brewfile

# - vscodefile:
#    file: Vscodefile
#    insiders: true

- shell:
    - [pwd]
    - [git submodule update --init --recursive, Installing submodules]
