require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*'
    - '.rvm/gems/*'
    - 'db/schema.rb'
    - 'spec/cassettes/*'

Rails/UnknownEnv:
  Environments:
    - production
    - staging
    - development
    - test

Rails/FilePath:
  EnforcedStyle: slashes

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/BlockLength:
  Max: 35
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
    - 'db/**/*'
  ExcludedMethods: ['group', 'context']

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Exclude:
    - 'db/**/*'
    - 'spec/**/*'

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

RSpec/ExampleLength:
  Max: 25

RSpec/MultipleExpectations:
  Max: 5

RSpec/DescribeClass:
  Enabled: false
