# frozen_string_literal: true

source 'https://rubygems.org'

# Core Application
ruby '2.5.7' # Specified ruby version
gem 'mysql2', '0.5.2' # Database technology for application
gem 'rails', '6.0.2.1' # Current framework used for application

# Environment

# Backend

# Frontend
# gem 'webpacker', '~> 4.2.2' # Preferred Asset Manager used for all client-side assets. Replaces the asset pipeline

# Caching and Performance
gem 'dalli', '~> 2.7.10' # Preferred client for memcaching to improve the performance of this application

# Errors and Logging
gem 'sentry-raven' # Preferred server error reporting client.
# NOTE: This application is currently using the cloud instance:
# https://sentry.io`

# Performance and Static Analysis
gem 'brakeman'
gem 'fasterer'
gem 'rails_best_practices'
gem 'traceroute'

gem 'debase-ruby_core_source'
gem 'htmlbeautifier'
gem 'shutup'
gem 'dotenv-rails'
gem 'rubocop'
gem 'rubocop-performance'
gem 'rubocop-rails'
gem 'rubocop-rspec'
gem 'solargraph'
