SHOW_ELAPSED_TIME: true
JAVASCRIPT_DEFAULT_STYLE: prettier
LINTER_RULES_PATH: /
JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
CSS_STYLELINT_CONFIG_FILE: LINTER_DEFAULT
YAML_YAMLLINT_CONFIG_FILE: LINTER_DEFAULT
# REPORT_OUTPUT_FOLDER: /coverage/linting
# LOG_FILE: mega-linter.log
IGNORE_GENERATED_FILES: true
DISABLE_LINTERS:
  # Linters
  # Prevents false positives with stylelint.
  - CSS_SCSS_LINT
  - C_CPPLINT
  - CLOJURE_CLJ_KONDO
  - COFFEE_COFFEELINT
  - CPP_CPPLINT
  - CSHARP_DOTNET_FORMAT
  - CSHARP_CSHARPIER
  - DART_DARTANALYZER
  - GO_GOLANGCI_LINT
  - GO_REVIVE
  - GROOVY_NPM_GROOVY_LINT
  - JAVA_CHECKSTYLE
  - JAVA_PMD
  - KOTLIN_KTLINT
  - LUA_LUACHECK
  - MAKEFILE_CHECKMAKE
  - PERL_PERLCRITIC
  - PYTHON_PYLINT
  - PYTHON_BLACK
  - PYTHON_FLAKE8
  - PYTHON_ISORT
  - PYTHON_BANDIT
  - PYTHON_MYPY
  - PYTHON_PYRIGHT
  - R_LINTR
  - RAKU_RAKU
  - RUST_CLIPPY
  - SALESFORCE_SFDX_SCANNER_APEX
  - SALESFORCE_SFDX_SCANNER_AURA
  - SALESFORCE_SFDX_SCANNER_LWC
  - SCALA_SCALAFIX
  - SQL_TSQLLINT
  - SWIFT_SWIFTLINT
  - VBDOTNET_DOTNET_FORMAT
  # Formatters
  - GRAPHQL_GRAPHQL_SCHEMA_LINTER
  - HTML_DJLINT
  # Prevents false positives with JSON_ESLINT_PLUGIN_JSONC
  - JSON_JSONLINT
  - LATEX_CHKTEX
  - RST_RST_LINT
  - RST_RSTCHECK
  # Tooling
  - ANSIBLE_ANSIBLE_LINT
  - ARM_ARM_TTK
  - BICEP_BICEP_LINTER
  - CLOUDFORMATION_CFN_LINT
  - EDITORCONFIG_EDITORCONFIG_CHECKER
  - GHERKIN_GHERKIN_LINT
  - PUPPET_PUPPET_LINT
  - SNAKEMAKE_LINT
  - SNAKEMAKE_SNAKEFMT
  - TEKTON_TEKTON_LINT
  - TERRAFORM_TFLINT
  - TERRAFORM_TERRASCAN
  - TERRAFORM_TERRAGRUNT
  - TERRAFORM_TERRAFORM_FMT
  - TERRAFORM_CHECKOV
  - TERRAFORM_KICS
  - COPYPASTE_JSCPD
  - REPOSITORY_SYFT
  - BASH_EXEC
  # - BASH_SHELLCHECK
  # - BASH_SHFMT
  # - JSX_ESLINT
  # - PHP_PHPCS
  # - PHP_PHPSTAN
  # - PHP_PSALM
  # - PHP_PHPLINT
  # - RUBY_RUBOCOP
  # - SQL_SQL_LINT
  # - SQL_SQLFLUFF
  # - TSX_ESLINT
  # - TYPESCRIPT_ES
  # - TYPESCRIPT_STANDARD
  # - TYPESCRIPT_PRETTIER
  # - CSS_STYLELINT
  # - ENV_DOTENV_LINTER
  # - HTML_HTMLHINT
  # - JSON_ESLINT_PLUGIN_JSONC
  # - JSON_V8R
  # - JSON_PRETTIER
  # - JSON_NPM_PACKAGE_JSON_LINT
  # - MARKDOWN_MARKDOWNLINT
  # - MARKDOWN_MARKDOWN_LINK_CHECK
  # - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  # - PROTOBUF_PROTOLINT
  # - RST_RSTFMT
  # - XML_XMLLINT
  # - YAML_PRETTIER
  # - YAML_YAMLLINT
  # - YAML_V8R
  # - ACTION_ACTIONLINT
  # - REPOSITORY_GITLEAKS
  # - REPOSITORY_GOODCHECK
  - REPOSITORY_SECRETLINT
  # - SPELL_MISSPELL
  # - SPELL_CSPELL
  # - SPELL_PROSELINT
  # Not included in Cupcake:
  # - POWERSHELL_POWERSHELL
  # - POWERSHELL_POWERSHELL_FORMATTER
  # - MARKDOWN_REMARK_LINT

DISABLE_ERRORS_LINTERS:
  - COPYPASTE_JSCPD
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - REPOSITORY_GITLEAKS
  - REPOSITORY_DEVSKIM
  - REPOSITORY_CHECKOV
  - REPOSITORY_TRIVY
  - REPOSITORY_KICS
  - ACTION_ACTIONLINT
  - DOCKERFILE_HADOLINT
  - JSON_JSONLINT
  - POWERSHELL_POWERSHELL
  - SPELL_CSPELL
  - YAML_YAMLLINT
