- defaults:
    link:
      relink: true

- clean: ['~']
- create:
    - ~/downloads
    - ~/downloads/databases
    - ~/alfred
    - ~/Library/LaunchAgents
    - ~/.git-template-directory
    - ~/.git-template-directory/hooks
    - ~/.git-template-directory/.github
    - ~/Documents/AMU
    - ~/Documents/AMU/repos
    - ~/Documents/AMU/repos/amu-development-team
    - ~/Documents/AMU/repos/amu-digital-products
    - ~/Documents/AMU/repos/amu-digital-services
    - ~/Documents/AMU/repos/amu-admins
- shell:
    - xcode-select --install || true
    - echo 'Xcode - Ready to go...'
    - echo ''
- brewfile:
    - Brewfile
- link:
    ~/Brewfile: Brewfile
    ~/Brewfile.lock.json: Brewfile.lock.json
- shell:
    - brew --version
    - echo 'General Software and Applications (via homebrew) - Ready to go...'

# Shell - Oh My ZSH, Custom plugins, themes, aliases, etc.
- shell:
    - description: 'Command Line Oh My Zsh - Ready to go...'
      command: './onboarding_bin/install-oh-my-zsh.sh'
      stdout: true
      stderr: true
- link:
    ~/.envrc:
      force: true
      path: .envrc
    ~/.zlogin:
      force: true
      path: shell/.zlogin
      stdout: true
    ~/.theme.zsh:
      force: true
      path: shell/.theme.zsh
    ~/.plugins.zsh:
      force: true
      path: shell/.plugins.zsh
    ~/.functions.zsh:
      force: true
      path: shell/.functions.zsh
    ~/.aliases.zsh:
      force: true
      path: shell/.aliases.zsh
    ~/iterm-profile-abarrows.json:
      force: true
      path: shell/iterm-profile-abarrows.json
    ~/iterm-profile-abarrows.itermkeymap:
      force: true
      path: shell/iterm-profile-abarrows.itermkeymap
    ~/com.googlecode.iterm2.plist:
      force: true
      path: shell/com.googlecode.iterm2.plist
    ~/.iterm2_shell_integration.zsh:
      force: true
      path: shell/.iterm2_shell_integration.zsh
    ~/.zshrc:
      force: true
      path: shell/.zshrc
- shell:
    # iTerm Configuration, Profile, and Settings
    # Specify the preferences directory
    - [
        defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string '~/',
      ]
    # Tell iTerm2 to use the custom preferences in the directory
    - defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

# Mac OSX
- shell:
    # Finder: show hidden files by default
    - defaults write com.apple.finder AppleShowAllFiles -bool true
    # Automatically hide and show the Dock
    - defaults write com.apple.dock autohide -bool true
    # Display full POSIX path as Finder window title
    - defaults write com.apple.finder _FXShowPosixPathInTitle -bool true
    # Disable the sound effects on boot
    # - sudo nvram SystemAudioVolume=" "

# - link:
#     '~/Library/Application Support/Alfred/Alfred.alfredpreferences/preferences/advanced/prefs.plist':
#     ~/operating_system/Alfred.alfredpreferences/preferences/advanced/prefs.plist
# - link:
#     - '~/Library/Application Support/Alfred/Alfred.alfredpreferences/preferences/appearance/options/prefs.plist':
#     ~/operating_system/Alfred.alfredpreferences/preferences/appearance/options/prefs.plist
# - link:
#     '~/Library/Application
#     Support/Alfred/Alfred.alfredpreferences/preferences/features/1password/prefs.plist':
#     ~/operating_system/Alfred.alfredpreferences/preferences/features/1password/prefs.plist
# - link:
#     '~/Library/Application
#     Support/Alfred/Alfred.alfredpreferences/preferences/features/clipboard/prefs.plist':
#     ~/operating_system/Alfred.alfredpreferences/preferences/features/clipboard/prefs.plist
# - link:
#     '~/Library/Application
#     Support/Alfred/Alfred.alfredpreferences/preferences/features/contacts/email/prefs.plist':
#     ~/operating_system/Alfred.alfredpreferences/preferences/features/contacts/email/prefs.plist
#     '~/Library/Application
#     Support/Alfred/Alfred.alfredpreferences/preferences/features/defaultresults/prefs.plist':
#     ~/operating_system/Alfred.alfredpreferences/preferences/features/defaultresults/prefs.plist
#     '~/Library/Application
#     Support/Alfred/Alfred.alfredpreferences/preferences/features/filesearch/actions/prefs.plist':
#     ~/operating_system/Alfred.alfredpreferences/preferences/features/filesearch/actions/prefs.plist
#     '~/Library/Application
#     Support/Alfred/Alfred.alfredpreferences/preferences/features/filesearch/navigation/prefs.plist':
#     ~/operating_system/Alfred.alfredpreferences/preferences/features/filesearch/navigation/prefs.plist
#     '~/Library/Application
#     Support/Alfred/Alfred.alfredpreferences/preferences/features/filesearch/quicklook/prefs.plist':
#     ~/operating_system/Alfred.alfredpreferences/preferences/features/filesearch/quicklook/prefs.plist
#     '~/Library/Application
#     Support/Alfred/Alfred.alfredpreferences/preferences/features/itunes/prefs.plist':
#     ~/operating_system/Alfred.alfredpreferences/preferences/features/itunes/prefs.plist
#     '~/Library/Application
#     Support/Alfred/Alfred.alfredpreferences/preferences/prefs.plist':
#     ~/operating_system/Alfred.alfredpreferences/preferences/prefs.plist
#     '~/Library/Application
#     Support/Alfred/Alfred.alfredpreferences/snippets/Github/info.plist':
#     ~/operating_system/Alfred.alfredpreferences/snippets/Github/info.plist

# Version Control
- link:
    ~/.onboarding_bin: onboarding_bin
    /usr/local/bin/pathChecker.sh: onboarding_bin/pathChecker.sh
    ~/.gitconfig:
      force: true
      path: version-control/.git-template-directory/.gitconfig
    ~/.git-template-directory/.github/CODEOWNERS: version-control/.git-template-directory/.github/CODEOWNERS
    ~/.git-template-directory/hooks/prepare-commit-msg: version-control/.git-template-directory/hooks/prepare-commit-msg
    ~/.git-template-directory/.gitignore: version-control/.git-template-directory/.gitignore
    ~/.bitbucket: version-control/.bitbucket

# Virtualized Environment
- link:
    ~/.dockerignore: virtualized_environments/.dockerignore

# General Software Engineering
- link:
    ~/.editorconfig: engineering/formatters/.editorconfig

    # General CSS and Style Linters
    ~/.stylelintrc.json: engineering/css/.stylelintrc.json
    ~/.stylelintrcignore: engineering/css/.stylelintrcignore
    # ~/postcss.config.js: engineering/postcss.config.js

    # General Formatters
    ~/.prettierrc.json: engineering/formatters/.prettierrc.json
    ~/.prettierignore: engineering/formatters/.prettierignore
    ~/.htmlhintrc.json: engineering/formatters/.htmlhintrc.json
- shell:
    - echo 'General Software Engineering - Ready to go...'

# Javascript and React
- link:
    # Node Versions
    ~/.nvmrc: engineering/javascript/.nvmrc
    ~/.npmignore: engineering/javascript/.npmignore
    # General Javascript Linters
    ~/.eslintrc.json: engineering/javascript/react/.eslintrc.json
    ~/.eslintignore: engineering/javascript/react/.eslintignore
- shell:
    - echo 'Node/React - Ready to go...'

# Ruby on Rails
- link:
    ~/.rubocop.yml: engineering/ruby/.rubocop.yml
    ~/.gemrc: engineering/ruby/.gemrc
    ~/.mkshrc: engineering/ruby/.mkshrc
    ~/.rvmrc: engineering/ruby/.rvmrc
    ~/.ruby-version: engineering/ruby/.ruby-version
    ~/.ruby-gemset: engineering/ruby/.ruby-gemset
    ~/.solargraph.yml: engineering/ruby/.solargraph.yml

- shell:
    - echo 'Ruby on Rails - Ready to go...'

# Python
- link:
    ~/Pipfile: engineering/python/Pipfile
    ~/Pipfile.lock: engineering/python/Pipfile.lock
    # ~/.pyenv:
    #   path: python/.pyenv
    #   create: true
- shell:
    - echo 'Python - Ready to go...'

# Wordpress - https://localwp.com/releases/
# - shell:
# - sh -c curl -fsSL https://cdn.localwp.com/releases-stable/6.0.0+5444/local-6.0.0-mac.dmg

# Databases
# TODO: Getting permission error when trying to symlink to LaunchAgents.  Do
# this manually.
# - link:
# '~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist':
# path: /usr/local/opt/postgresql/homebrew.mxcl.postgresql.plist
- shell:
    - launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
    - echo 'PostgresQL and MySQL Databases - Ready to go...'

# IDE - VS Code
- link:
    '~/Library/Application Support/code/User/settings.json':
      path: engineering/ide/.vscode/settings.json
      force: true
    '~/Library/Application Support/code/User/keybindings.json':
      path: engineering/ide/.vscode/keybindings.json
      force: true
    '~/Library/Application Support/code/User/tasks.json':
      path: engineering/ide/.vscode/tasks.json
      force: true
    '~/Library/Application Support/code/User/launch.json':
      path: engineering/ide/.vscode/launch.json
      force: true
- shell:
    - code --list-extensions > engineering/ide/.vscode/extensions.txt
- vscodefile:
    file: engineering/ide/.vscode/extensions.txt
    insiders: false
- shell:
    - echo 'VS Code - Ready to go...'
    - xcode-select --install || true
    - echo 'Xcode - Ready to go...'
    - echo "[INFO] • iTerm2 profile - Open iTerm2 -> Preferences -> Profiles -> Other Actions -> Import JSON Profiles - Select the profile from ~/iterm-profile-front-end-engineering.json"
    - echo "[INFO] • iTerm2 keymap - Open iTerm2 -> Preferences -> Keys -> ⚙ Presets... -> Import... Select the keymap from ~/iterm-profile-front-end-engineering.json"
    - source ~/.zshrc
    - echo 'Shell/ZSH - Custom theme, plugins, aliases, etc. installed. Ready to go...'
    - echo 'Sourcing your zshrc! You are ready to rock and roll...'
