- defaults:
    link:
      relink: true

- clean: ['~']
- create:
    - ~/downloads
    - ~/.nvm
    - ~/Library/LaunchAgents
# Shell - Oh My ZSH
- shell:
    - command: oh-my-zsh/tools/install.sh
      stdout: true
      stderr: true
      description: Installing oh-my-zsh
# Shell - Custom plugins, themes, aliases, etc.
- link:
  ~/.p10k.zsh: shell/.p10k.zsh
  ~/.zshrc: shell/.zshrc
  ~/.zlogin: shell/.zlogin
  ~/.oh-my-zsh/custom/.zshrc_theme.zsh: shell/.zshrc_theme.zsh
  ~/.oh-my-zsh/custom/.zshrc_plugins.zsh: shell/.zshrc_plugins.zsh
  ~/.oh-my-zsh/custom/.zshrc_functions.zsh: shell/.zshrc_functions.zsh
  ~/.oh-my-zsh/custom/.zshrc_aliases.zsh: shell/.zshrc_aliases.zsh
  ~/.iterm2_shell_integration.zsh: shell/.iterm2_shell_integration.zsh
# Version Control
- link:
    ~/.acb_bin: acb_bin
    /usr/local/bin/pathChecker.sh: acb_bin/pathChecker.sh
    ~/.bitbucket: version-control/.bitbucket
    ~/.gitconfig: version-control/.gitconfig
    ~/.gitconfig-professional: version-control/.gitconfig-professional
# Homebrew General Software and Applications
- link:
    ~/Brewfile: Brewfile
    ~/Brewfile.lock.json: Brewfile.lock.json
- brewfile:
    - Brewfile
# General Software Engineering
- link:
    ~/.electron-gyp: node/.electron-gyp
    ~/.node: node/.nvmrc
    ~/.npmignore: node/.npmignore
    ~/.bundle: ruby/.bundle
    ~/package.json: engineering/package.json
    ~/yarn.lock: engineering/yarn.lock
    ~/.editorconfig: engineering/.editorconfig
    ~/.eslintrc.json: engineering/.eslintrc.json
    ~/.eslintignore: engineering/.eslintignore
    ~/postcss.config.js: engineering/postcss.config.js
    ~/.prettierrc.json: engineering/.prettierrc.json
    ~/.prettierignore: engineering/.prettierignore
    ~/.postcssrc.yml: engineering/.postcssrc.yml
    ~/.stylelintrc.json: engineering/.stylelintrc.json
    ~/.rubocop.yml: ruby/.rubocop.yml
    ~/.gem: ruby/.gem
    ~/.gemrc: ruby/.gemrc
    ~/.mkshrc: ruby/.mkshrc
    # ~/.pyenv:
    #   path: python/.pyenv
    #   create: true
# Databases
# TODO: Getting permission error when trying to symlink to LaunchAgents.  Do
# this manually.
# - link:
# '~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist':
# path: /usr/local/opt/postgresql/homebrew.mxcl.postgresql.plist
- shell:
    - launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
# IDE - VS Code
- link:
    '~/Library/Application Support/code/User/settings.json':
      path: .vscode/settings.json
      force: true
    '~/Library/Application Support/code/User/keybindings.json':
      path: .vscode/keybindings.json
      force: true
    '~/Library/Application Support/code/User/tasks.json':
      path: .vscode/tasks.json
    '~/Library/Application Support/code/User/launch.json':
      path: .vscode/launch.json
    '~/Library/Application Support/code/User/snippets':
      path: .vscode/snippets
      create: true
- shell:
    - code --list-extensions > .vscode/extensions.txt
- vscodefile:
    file: .vscode/extensions.txt
    insiders: false
- shell:
    - xcode-select --install || true
    - source ~/.zshrc
    - echo 'Sourcing your zshrc! You are ready to rock and roll...'
