- defaults:
    link:
      relink: true

- clean: ['~']

- shell:
    - git submodule update --init --recursive
    - sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" || true

- link:
    ~/.acb_bin: acb_bin
    /usr/local/bin/pathChecker.sh: acb_bin/pathChecker.sh
    ~/.bitbucket: .bitbucket
    ~/.gitconfig: version-control/.gitconfig
    ~/.gitconfig-professional: version-control/.gitconfig-professional
    ~/.p10k.zsh: .p10k.zsh
    ~/.zshrc: shell/.zshrc
    ~/.zlogin: shell/.zlogin
    ~/.zshrc_theme.zsh: shell/.zshrc_theme.zsh
    ~/.zshrc_plugins.zsh: shell/.zshrc_plugins.zsh
    ~/.zshrc_functions.zsh: shell/.zshrc_functions.zsh
    ~/.zshrc_aliases.zsh: shell/.zshrc_aliases.zsh
    ~/.electron-gyp: node/.electron-gyp
    ~/.node: node/.nvmrc
    ~/.npmignore: node/.npmignore
    ~/.bundle: ruby/.bundle
    ~/package.json: engineering/package.json
    ~/yarn.lock: engineering/yarn.lock
    ~/.editorconfig: engineering/.editorconfig
    ~/.eslintrc.json: engineering/.eslintrc.json
    ~/.eslintignore: engineering/.eslintignore
    ~/postcss.config.js: engineering/postcss.config.js
    ~/.prettierrc.json: engineering/.prettierrc.json
    ~/.prettierignore: engineering/.prettierignore
    ~/.postcssrc.yml: engineering/.postcssrc.yml
    ~/.stylelintrc.json: engineering/.stylelintrc.json
    ~/.rubocop.yml: ruby/.rubocop.yml
    ~/.gem: ruby/.gem
    ~/.gemrc: ruby/.gemrc
    ~/.mkshrc: ruby/.mkshrc
    # ~/.pyenv:
    #   path: python/.pyenv
    #   create: true
    ~/Brewfile: Brewfile
    ~/Brewfile.lock.json: Brewfile.lock.json
    ~/.iterm2_shell_integration.zsh: .iterm2_shell_integration.zsh

- create:
    - ~/downloads
    - ~/.nvm
    - ~/Library/LaunchAgents

- brewfile:
    - Brewfile

# VS Code
- link:
    '~/Library/Application Support/code/User/settings.json':
      path: .vscode/settings.json
      force: true
    '~/Library/Application Support/code/User/keybindings.json':
      path: .vscode/keybindings.json
      force: true
    '~/Library/Application Support/code/User/tasks.json':
      path: .vscode/tasks.json
    '~/Library/Application Support/code/User/launch.json':
      path: .vscode/launch.json
    '~/Library/Application Support/code/User/snippets':
      path: .vscode/snippets
      create: true
- shell:
    - code --list-extensions > .vscode/extensions.txt
- vscodefile:
    file: .vscode/extensions.txt
    insiders: false
# Databases
- link:
  '~/Library/LaunchAgents':
    path: /usr/local/opt/postgresql/*.plist
- shell:
    - launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist

- shell:
    - xcode-select --install || true
    - source ~/.zshrc
    - echo 'Sourcing your zshrc! You are ready to rock and roll...'
