- defaults:
    link:
      relink: true
      create: true
    shell:
      stdout: true
      stderr: true

- shell:
    - ["git submodule update --init --recursive", "Installing submodules"]
    - ["zsh", "resourcing the zshrc."]

- clean: ["~"]

- shell:
    - echo "Cleaning the config directory."
