// keys.js ======
module.exports = {
  APPLICATION_NAME: process.env.APPLICATION_NAME,
  APPLICATION_PORT: process.env.APPLICATION_PORT,
  APPLICATION_VERSION: process.env.APPLICATION_VERSION,
  APPLICATION_ENVIRONMENT: process.env.APPLICATION_ENVIRONMENT,
  NEXT_PUBLIC_DEPLOY_ENV: process.env.APPLICATION_ENVIRONMENT,
  NEXT_PUBLIC_APP_VERSION: process.env.APPLICATION_VERSION,
  NEXT_PUBLIC_DEPLOY_ENV: process.env.APPLICATION_ENVIRONMENT,
  NEXT_PUBLIC_APP_VERSION: process.env.APPLICATION_VERSION,
  STORYBOOK_PORT: process.env.STORYBOOK_PORT,
};
