---
linters:
  FinalNewline:
    enabled: true
    exclude:
      - '**vendor/bundle/**'
  RightTrim:
    enabled: true
    enforced_style: '-'
    exclude:
      - '**vendor/bundle/**'
  SelfClosingTag:
    enabled: true
    enforced_style: 'always'
    exclude:
      - '**vendor/bundle/**'
  AllowedScriptType:
    enabled: true
    allowed_types:
      - 'application/json'
      - 'text/javascript'
      - 'text/html'
    allow_blank: false
    disallow_inline_scripts: false
    exclude:
      - '**vendor/bundle/**'
  DeprecatedClasses:
    enabled: true
    exclude:
      - '**vendor/bundle/**'
    # exclude:
    # - "app/views/shared/deprecated/**"
    # rule_set:
    # - deprecated: ['badge[-_\w]*']
    # suggestion: "Use the ui_badge() component instead."
  # CustomLinter:
  # enabled: true
  # custom_message: We suggest you change this file.
  ErbSafety:
    enabled: true
    better_html_config: .better-html.yml
    exclude:
      - '**vendor/bundle/**'
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingBlankLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Metrics/LineLength:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
